name: task_manager
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2-171.0.dev <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_alarm_clock: ^0.0.2
  flutter_circular_chart: ^0.1.0
  get: ^4.6.5
  gif: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  path_provider: ^2.0.11
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  workmanager: ^0.5.1

dev_dependencies:
  build_runner: ^2.2.0

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/gif/
  fonts:
    - family: slam
      fonts:

       
        - asset: assets/fonts/Fontspring-DEMO-slam-bold.otf
        - asset: assets/fonts/Fontspring-DEMO-slam-extrabold.otf
        - asset: assets/fonts/Fontspring-DEMO-slam-oblique-regular.otf
          weight: 900
    - family: SourceCodePro
      fonts:

        - asset: "assets/Source_Code_Pro/SourceCodePro-ExtraBold.ttf"
        - asset: "assets/Source_Code_Pro/SourceCodePro-Regular.ttf"
        - asset: "assets/Source_Code_Pro/SourceCodePro-Bold.ttf"
        - asset: "assets/Source_Code_Pro/SourceCodePro-Medium.ttf"
        # - asset: "/assets/Source_Code_Pro/"
        # - asset: "/assets/Source_Code_Pro"
        # - asset: "/assets/Source_Code_Pro"
          weight: 900
